---
title: "reveal.js TUBAF"
subtitle: "A customized TU Bergakademie Freiberg theme for Quarto slides"
format: tubaf-revealjs
author: Ralph-Uwe Börner
date: last-modified
---

## Editing the presentation

### Edit the title slide

The information shown in the title slide can be edited by changing the metadata in 
`template.qmd`.

## Navigation

Navigation is mostly done via keyboard shortcuts.

- Use spacebar, or vim bindings `j`, `k`, `h`, `l`, for navigation between slides.
- `m` to open menu bar for other presentation tools.

## Overview and Zoom

Press `o` to toggle overview mode.

<br/>

Hold down the `Alt` key (or `Option` on MacOS) and click on any element to zoom towards it---try it now on this slide.

## Speaker View

Press `s` (or use the presentation menu) to open speaker view

::: {.notes}

Speaker notes go here.
:::

## LaTeX Equations

[MathJax](https://www.mathjax.org/) rendering of equations to HTML.

Equation label and reference are supported too. For example, @eq-sincos shows 

$$
1=\cos^2 x + \sin^2 x
$${#eq-sincos}

This is done via:

```tex
\begin{equation}
1=\cos^2 x + \sin^2 x
\end{equation}{#eq-sincos}
```

Referencing the equation is as simple as `@eq-sincos`.

## Incremental Lists

Lists can optionally be displayed incrementally:

::: incremental
-   First item
-   Second item
-   Third item
:::

. . .

<br/> Insert pauses to make other types of content display incrementally.




## More Information

You can learn more about controlling the appearance of RevealJS output here: <https://quarto.org/docs/presentations/revealjs/>

